### ISSUE TITLE
jj tries to push branch to @origin even though it's tracking @priv

### ISSUE THREAD

**Issue by colemickens** [martinvonz/jj#3050] opened 2024-02-14 22:12 UTC
## Description

jj git push seems to pick the wrong remote to push to for tracked branches. **This is quite scary, luckily the one time I accidentally pushed without specifying remote, I was blocked from pushing to a different, protected branch on origin, which prevented the private feature branch from getting pushed publicly.**

I have a repo with two remote repos `project` and `project-priv`, added as `origin` and `priv` origins.

```
> jj branch list
colemickens/foo-spike: onlxxxuu deadb33f (empty) test commit
  @priv (behind by 1 commits): swyyyvst deadbeef foo
...
```

but...

```
>  jj git push --dry-run
Branch changes to push to origin:
  Add branch colemickens/foo-spike to deadbeef
Dry-run requested, not pushing.
```

I can't tell if this is a feature request or a bug.

**Comment by ilyagr** [comment] 2024-02-14 23:22
This seems expected to me, so I think this is a feature request. We should probably try to improve this.

`jj git push` always pushes to the default remote if you don't specify one. Since a local branch can track more than one remote, I'm not sure whether it could push to "the" tracked branch by default.

Some possibilities that come to mind:

- We should probably have a way to forbid pushing a branch to the remote even if the branch doesn't yet exist there or jj doesn't know about it. If `branch@origin` did exist, `jj branch untrack branch@origin` would prevent `push` from ever pushing to that remote.
- In principle, we could have a "safe mode" where `jj git push` refuses to create branches unless you pass a flag to it. It would probably apply to branch deletion too.

**Comment by yuja** [comment] 2024-02-15 03:19
Perhaps, this is dupe of #1278. iirc, Git has a concept that a local branch is associated with one tracked remote to push.

**Comment by yuja** [comment] 2024-03-07 02:56
(closed as duplicates)

**Closed by yuja** 2024-03-07 02:56 UTC
