### ISSUE TITLE
FR: Add a verbose (show diff) option to describe/commit/split

### ISSUE THREAD

**Issue by jalil-salame** [martinvonz/jj#4087] opened 2024-07-14 21:02 UTC
**Is your feature request related to a problem? Please describe.**
I like reviewing the diffs when describing a change to catch mistakes (e.g. wrong split order, or including debug statements).

**Describe the solution you'd like**
Add a verbose CLI option (in the spirit of `git commit --verbose`) that adds a commented out diff to the default commit message body.

**Describe alternatives you've considered**
I can't think of any alternatives to this behavior, but feel free to add some.

**Additional context**
`man git-config`:
```
       -v, --verbose

           Show unified diff between the HEAD commit and what would be committed at the bottom of the commit message template to help the user describe the commit by reminding what changes the commit
           has. Note that this diff output doesn’t have its lines prefixed with #. This diff will not be a part of the commit message. See the commit.verbose configuration variable in git-config(1).

           If specified twice, show in addition the unified diff between what would be committed and the worktree files, i.e. the unstaged changes to tracked files.
```

**Comment by ilyagr** [comment] 2024-07-14 22:40
Seems like a good idea to me.

The one thing I would change is the option name. I think `--verbose` now generally tends to mean having a CLI tool show detailed output, like our `--debug` (which was previously called `--verbose`, but we might want to use `--verbose` again sometime, who knows).

One option for a name is `--patch` or `--show-patch`. Perhaps we can come up with something better.

This also might be a duplicate, I think I remember a similar discussion before, but I'm not sure whether it was in an issue or on Discord.

**Comment by yuja** [comment] 2024-07-15 01:31
Closing as duplicate of #1946, and #3470 has some attempt.

**Closed by yuja** 2024-07-15 01:31 UTC
Labels: enhancement, good first issue
