### ISSUE TITLE
Use of scm-diff-editor will create an extra JJ-INSTRUCTIONS change in `jj split`

### ISSUE THREAD

**Issue by ccll** [martinvonz/jj#4984] opened 2024-11-27 08:27 UTC
## Description

While the bug below has not been fixed, I'm trying to use the vanilla `scm-diff-editor` as said to work.
- #3702

It works on deleted files when `jj split`, but has another issue: a dummy JJ-INSTRUCTIONS appears as a change. 

## Steps to Reproduce the Problem

1. install scm-diff-editor
`cargo install scm-diff-editor`

2. set diff-editor to scm-diff-editor
```
[ui]
diff-editor = "scm-diff-editor"

[merge-tools.scm-diff-editor]
program = "scm-diff-editor"
edit-args = ["--dir-diff", "$left", "$right"]
```

3. `jj split`

## Expected Behavior

Just show the exact changes, nothing more, nothing less.

## Actual Behavior

![image](https://github.com/user-attachments/assets/4d1b8891-75f1-4a1d-a6a8-4ccf44c35b02)

## Specifications

- Platform: Windows 11
- Version: jj 0.23.0-5de285f5eb727b613434979cd9d83c30cabaffae

**Comment by arxanas** [comment] 2024-11-27 17:20
Does the file actually get committed? I had thought the file appears for all diff editors, and is ignored regardless of whether it gets selected.

**Comment by arxanas** [comment] 2024-11-27 19:00
> Does the file actually get committed? I had thought the file appears for all diff editors, and is ignored regardless of whether it gets selected.

If it's true that selecting/unselecting `JJ-INSTRUCTIONS` doesn't affect the outcome, then we should probably add a note to `JJ-INSTRUCTIONS` itself that it doesn't matter what you do with it.

It's also interesting that `JJ-INSTRUCTIONS` doesn't appear for the built-in editor. I don't recall if that was intentional or not. It would be nice if `scm-record` were intuitive enough to not require instructions, but I think that's not the case at present 🤣.

I also opened https://github.com/arxanas/scm-record/issues/78 to suggest adding a more-integrated way of providing help text with the built-in editor.

**Comment by ccll** [comment] 2024-11-28 05:59
> Does the file actually get committed? I had thought the file appears for all diff editors, and is ignored regardless of whether it gets selected.

Confirm that the `JJ-INSTRUCTIONS` file does NOT get committed, so it's just a little annoying rather than actual harmful.

**Comment by martinvonz** [comment] 2024-11-28 13:31
I think this is working as intended then. See https://martinvonz.github.io/jj/latest/config/#jj-instructions for how to disable the `JJ-INSTRUCTIONS` file. Feel free to reopen if you think there's something else we should do.

**Closed by martinvonz** 2024-11-28 13:31 UTC
Labels: 🐛bug, scm-record

**Comment by arxanas** [comment] 2024-11-28 20:34
@martinvonz I think action items here would be

- [ ] Update the instruction text to clarify that it won't be committed
- [ ] Update the instruction text to specify how to disable it

@ccll Would those have helped you in this case? Perhaps you're interested in trying the above?

**Comment by ccll** [comment] 2025-01-02 02:22
> @ccll Would those have helped you in this case? Perhaps you're interested in trying the above?

I've disabled the file with @martinvonz 's suggestion.
However I think your action 2 might be a great idea for anyone that missed the document like me.
