### ISSUE TITLE
Git submodules not ignored

### ISSUE THREAD

**Issue by istudyatuni** [martinvonz/jj#5005] opened 2024-11-30 12:16 UTC
## Description

[Changelog for v0.6.0](https://github.com/martinvonz/jj/releases/tag/v0.6.0) states that "Git submodules are now ignored completely", but that's not work (even on v0.6). Am I missing something?

## Steps to Reproduce the Problem

```bash
jj git init --colocate
git submodule add https://github.com/martinvonz/jj
jj st
```

## Expected Behavior
Only .gitmodules file is added

## Actual Behavior
All files from submodule are also added

## Specifications

- Platform: Linux
- Version: v0.12. Also tested on latest main (0ca6f00421f6f893e974e0f5349e126abd41a812 - Nov 30)

v0.6 tested with `nix shell 'github:martinvonz/jj?ref=v0.6.0'`

**Comment by yuja** [comment] 2024-11-30 12:48
Submodule support is pretty minimal. You need to do `git commit` before the change is snapshotted by `jj st`.

> All files from submodule also are added

Maybe we should ignore files in the nested repo, no matter if it is a submodule or not.

**Comment by yuja** [comment] 2024-12-10 03:27
It at least works as intended, so closing the issue.

**Closed by yuja** 2024-12-10 03:27 UTC
