### ISSUE TITLE
tabs break rendering in diff-editor

### ISSUE THREAD

**Issue by Zoybean** [martinvonz/jj#4276] opened 2024-08-15 14:04 UTC
## Description
Tab characters in text files cause issues in rendering, with some areas of the display not being updated on fold / scroll

## Steps to Reproduce the Problem

1. `jj init`
2. `echo $'\t\t\tabc' > foo.txt`
3. `jj split`
4. press `f` to expand the root node
5. press `f` again to collapse the root node

## Expected Behavior
The screen shows the same content after folding that it did before unfolding.

## Actual Behavior
Some of the content of the hidden node is still shown after folding the diff.

## Specifications

- Platform: Linux Mint 22
- Version: jj 0.20.0-78c0128ec3b70c72810251c42847c1efa1f83a31

**Comment by bnjmnt4n** [comment] 2024-08-15 14:11
This is a duplicate of https://github.com/martinvonz/jj/issues/4001.

**Closed** 2024-08-15 14:17 UTC
