### ISSUE TITLE
FR: Allow creating default flags per command

### ISSUE THREAD

**Issue by matts1** [martinvonz/jj#2621] opened 2023-11-23 04:14 UTC
**Is your feature request related to a problem? Please describe.**
I often want to set a default set of options to use for a command. For example:
* `rebase --skip-empty`
* `log --no-pager` (I like paging for diffs but not for logs)

This can currently be achieved via an alias, but you cannot alias an existing command to something (eg. `log = ["log", "--no-pager"]`).

**Describe the solution you'd like**
```
[command-defaults.log]
pager = false

[command-defaults.rebase]
skip_empty = true
```

We'd then simply modify clap to use defaults from a function instead of a static value (which appears to be possible - https://github.com/clap-rs/clap/issues/1634#issuecomment-575885740)

**Describe alternatives you've considered**
Aliasing log to log could work, and might be simpler to implement, but what does the following do:
```
[aliases]
log = ["log", "--no-pager"]
log-head = ["log", "@"]
```

In this scenario, it's unclear whether we should use `log --no-pager @` or `log @`.

**Comment by martinvonz** [comment] 2023-11-23 08:15
This is a duplicate of the closed #1509. See the explanation there, but feel free to comment there (or here) if you think we missed anything.

**Closed by martinvonz** 2023-11-23 08:15 UTC
