### ISSUE TITLE
FR: `log.excludeDecoration` in Git-backed repos should be set to refs/jj/*

### ISSUE THREAD

**Issue by mlcui-google** [martinvonz/jj#1884] opened 2023-07-18 06:41 UTC
In a git-backed repo (not colocated, although this probably happens with colocated repos too), running `git log` shows `refs/jj/keep/*` tags in commits.

To work around this, set `log.excludeDecoration` to `refs/jj/*` in the git config. I believe that jj doesn't set any git configuration options, so perhaps a git-branchless-like approach (create a separate jj-specific config file and include that from) could work here to make "uninstallation" easy if needed.

**Comment by InCogNiTo124** [comment] 2024-01-22 20:14
I could take a stab at this this week

**Comment by InCogNiTo124** [comment] 2024-01-24 21:50
I actually can't reproduce this with a fresh repo.

repo setup:
```
$ cd /tmp
$ git init test
$ cd test
$ echo "test" > readme.md
$ git add readme.md
$ git commit -m 'commit 1'
$ git log
commit 6f4650ea090d2a567f9320cb10656040352e0282 (master)
Author: InCogNiTo124 <msmetko@msmetko.xyz>
Date:   Wed Jan 24 22:43:58 2024 +0100

    commit 1
```

adding jj:
```
$ jj init --git-repo=.
$ jj log
◉  vyvzsvpn msmetko@msmetko.xyz 2024-01-24 22:43:58.000 +01:00 master 6f4650ea
│  commit 1
◉  zzzzzzzz root() 00000000
$ echo "change" > readme.md
$ jj commit
$ jj log
@  oozsrpmx msmetko@msmetko.xyz 2024-01-24 22:44:26.000 +01:00 39ebd6a1
│  (empty) (no description set)
◉  kllqsywo msmetko@msmetko.xyz 2024-01-24 22:44:26.000 +01:00 HEAD@git bae46455
│  final
◉  vyvzsvpn msmetko@msmetko.xyz 2024-01-24 22:43:58.000 +01:00 master 6f4650ea
│  commit 1
◉  zzzzzzzz root() 00000000
$ git log
commit bae46455e12acb36abbc7e975bac99a5e6b84ce6 (HEAD)
Author: InCogNiTo124 <msmetko@msmetko.xyz>
Date:   Wed Jan 24 22:44:02 2024 +0100

    final

commit 6f4650ea090d2a567f9320cb10656040352e0282 (master)
Author: InCogNiTo124 <msmetko@msmetko.xyz>
Date:   Wed Jan 24 22:43:58 2024 +0100

    commit 1
```

I am not sure at which step should I see `refs/jj/...`

**Comment by martinvonz** [comment] 2024-01-24 22:26
I can't either. Looks like the behavior changed in git in https://github.com/git/git/commit/92156291ca82ae4f4ad09fde8181c5f2b7dba6ca (2.38.0, released oct 2022). So I'm going to guess that we just didn't have that version at Google when @mlcui-google reported this bug.

**Comment by martinvonz** [comment] 2024-01-24 22:27
@InCogNiTo124, feel free to close this bug unless you're going to spend more time on it.

**Comment by InCogNiTo124** [comment] 2024-01-25 00:19
I won't be investing any more time, but I seem to lack permissions to close this issue

**Closed** 2024-01-25 00:20 UTC
Labels: good first issue
