### ISSUE TITLE
FR: Print "remote:" messages when pushing new branch to git repo

### ISSUE THREAD

**Issue by NoahTheDuke** [martinvonz/jj#3236] opened 2024-03-06 19:29 UTC
**Is your feature request related to a problem? Please describe.**
When using `git`, if I create a new branch and say `git push`, some forges will send back messages that allow me to open a new PR/MR on the forge for that branch. For example:

```
noah ~/personal/temp
$ git switch -c nb/example
Switched to a new branch 'nb/example'
noah ~/personal/temp
$ touch example
noah ~/personal/temp
$ git add example
noah ~/personal/temp
$ git commit -m 'ignore me'
[nb/example 571c1446] ignore me
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 example
noah ~/personal/temp
$ git push
Enumerating objects: 45, done.
Counting objects: 100% (43/43), done.
Delta compression using up to 11 threads
Compressing objects: 100% (25/25), done.
Writing objects: 100% (29/29), 3.54 KiB | 3.54 MiB/s, done.
Total 29 (delta 20), reused 4 (delta 2), pack-reused 0
remote:
remote: To create a merge request for nb/example, visit:
remote:   https://gitlab.com/crossbeam/temp/-/merge_requests/new?merge_request%5Bsource_branch%5D=nb%2Fexample
remote:
To gitlab.com:crossbeam/temp.git
 * [new branch]        nb/example -> nb/example
branch 'nb/example' set up to track 'origin/nb/example'.
```

At the end, there's the 3 lines starting with `remote:`, and the middle one is a link generated by Gitlab that I can copy-paste to automatically open an MR for this new branch.

**Describe the solution you'd like**
Display those messages somehow.

**Describe alternatives you've considered**
Do nothing.

**Comment by julienvincent** [comment] 2024-03-13 22:21
I would also like! However I think this is a duplicate of https://github.com/martinvonz/jj/issues/1967

**Comment by NoahTheDuke** [comment] 2024-03-13 22:56
Oh good find, i didn't see that one

**Closed** 2024-03-13 23:00 UTC
Labels: polish🪒🐃
