### ISSUE TITLE
Builtin pager does not work when using Git Bash on Windows and `jj` panics

### ISSUE THREAD

**Issue by jennings** [martinvonz/jj#4182] opened 2024-07-30 18:33 UTC
## Description

When using the builtin pager on the MinTTY Git Bash on Windows, pagination panics:

```
$ RUST_BACKTRACE=1 jj
Hint: Use `jj -h` for a list of available commands.
Run `jj config set --user ui.default-command log` to disable this message.
thread '<unnamed>' panicked at cli\src\ui.rs:90:53:
called `Result::unwrap()` on an `Err` value: Setup(InvalidTerminal)
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at cli\src\ui.rs:74:37:
called `Result::unwrap()` on an `Err` value: Any { .. }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

## Steps to Reproduce the Problem

1. Open Git Bash from the start menu
2. `jj log`

## Suggestions

The failure seems to occur because stdout's `is_tty()` returns false, so Minus returns an `Err(SetupError(InvalidTerminal))`.

If possible, we can work around it, but we should also document that the user can avoid the problem by:

- Adding Git Bash to Windows Terminal. The configuration is:
  ```
  {
    "profiles": {
      "list": [
        ...
        {
          "guid": "{00000000-0000-0000-ba54-000000000002}",
          "commandline": "%PROGRAMFILES%/Git/bin/bash.exe -i -l",
          "icon": "%PROGRAMFILES%/Git/mingw64/share/git/git-for-windows.ico",
          "name" : "Bash",
          "startingDirectory" : "%USERPROFILE%"
        }
      ]
    }
  }
  ```
- Using PowerShell or cmd (preferrably in Windows Terminal, but the standard host will do as well)
- Disabling pagination (though who knows if another error will occur somewhere else)

**Comment by ilyagr** [comment] 2024-07-30 18:36
On discord, you suggested `winpty`. Does that work?

> Disabling pagination (though who knows if another error will occur somewhere else)

If the problem is just with our internal pager, we could disable it on that error.

**Comment by zschreur** [comment] 2024-07-30 19:52
fwiw when I went and followed these steps it fixed it for me: https://martinvonz.github.io/jj/latest/windows/#pagination

**Comment by jennings** [comment] 2024-07-30 21:27
> On discord, you suggested `winpty`. Does that work?

Whoops, yes. `winpty jj` also fixed it. I found that suggestion [in a similar issue in docker/for-win](https://github.com/docker/for-win/issues/1588).

**Comment by ilyagr** [comment] 2024-07-30 21:38
Is winpty a part of Git for Windows, Cygwin, or both? Can we expect the user to have it?

**Comment by jennings** [comment] 2024-07-30 22:08
```
$ where winpty
C:\Program Files\Git\usr\bin\winpty.exe
```

Looks like it ships with Git for Windows, so it should be accessible from Git Bash.

**Comment by ilyagr** [comment] 2024-07-30 22:31
It's less clear what to do here than I thought. It seems to me like a decent solution would require modifying `minus`.

The panic happens here:

https://github.com/martinvonz/jj/blob/51e11ff7e3be2e19ba63975be868c06075213e00/cli/src/ui.rs#L88-L91

If we remove that `unwrap()`, `jj` will continue chugging along and performing whatever command it's doing. (It does that now, as well, but hopefully not for long until the panic happens).

The easiest place to detect that `minus` encountered an error would be when the thread is joined in

https://github.com/martinvonz/jj/blob/51e11ff7e3be2e19ba63975be868c06075213e00/cli/src/ui.rs#L72-L75

but at that point `jj` is done with its operation, having put its output into the pager that will never print it. `minus` doesn't seem to provide a way to extract that data. If we can't print that data, I'm wondering whether the crash we see today (that hopefully usually happens before the `jj` operation completes) is the better outcome.

I think that, for a better behavior, we'd need `minus` to provide either a way for us to extract the data and print it directly to `stdout` (assuming that works) or a way to check that Minus is likely to succeed in the main thread, before running `dynamic_pager` in a separate thread.

**Comment by ilyagr** [comment] 2024-07-30 22:45
I filed https://github.com/AMythicDev/minus/issues/145, perhaps the `minus` people will have suggestions.

**Comment by ilyagr** [comment] 2024-08-03 02:24
According to @yuja (see https://github.com/martinvonz/jj/pull/4197#discussion_r1702422251), a few of my assumptions above were wrong. He thinks that the simpler design that notices the error in `finalize` can work.

**Comment by ilyagr** [comment] 2024-08-05 19:24
The current status: jj should no longer panic in this case and should print a sensible error.

Things may change further if we switch from minus to streampager as our built-in pager.

This seems good enough to close the issue, but feel free to reopen it open new ones. For instance, the new behavior should work but isn't well-tested.

**Closed** 2024-08-05 19:24 UTC
Labels: 🐛bug, 🪟Windows
