### ISSUE TITLE
`jj log` changes behaviour if a revision has a description vs not

### ISSUE THREAD

**Issue by hgezim** [martinvonz/jj#4514] opened 2024-09-20 23:11 UTC
## Expected Behavior

`jj log` should show me revisions no matter if they have a description or not

## Actual Behavior

```
$ jj
@  nuoxwrxz <myemail> 2024-09-20 16:54:11 e5598061
│  (empty) (no description set)
○  mqkpukly <myemail> 2024-09-20 15:11:31 HEAD@git 5923228d
...
$ jj describe -r yvltunkn
$ jj
○  yvltunkn <myemail> 2024-09-20 17:06:28 2060dd86
│  Some description
│  M .gitignore
│  M gemini.ts
│  M package.json
│ @  nuoxwrxz <myemail> 2024-09-20 16:54:11 e5598061
│ │  (empty) (no description set)
│ ○  mqkpukly <myemail> 2024-09-20 15:11:31 HEAD@git 5923228d
```

## Specifications

- Platform: MacOS
- Version: jj 0.20.0

**Comment by martinvonz** [comment] 2024-09-21 00:51
It's just the most recently created commit that shows at the top. It's unrelated to the description. I'll close this because it's working as intended, but feel free to reopen if you think we should change anything.

**Closed by martinvonz** 2024-09-21 00:51 UTC

**Comment by hgezim** [comment] 2024-09-21 05:14
@martinvonz I see, [describe creates a commit](https://martinvonz.github.io/jj/latest/glossary/#rewrite).

If I have commit <a> that's has a parent that's super old and commit <b> with a lot of young parents, I'd like to see both of these towards the top of the log (relatively close commit times). How would I achieve this?

**Comment by noahmayr** [comment] 2024-09-21 10:44
Play around with revsets: https://martinvonz.github.io/jj/latest/revsets/
You can also change the default log revset (defined here https://github.com/martinvonz/jj/blob/main/cli/src/config/revsets.toml#L6) by setting `revsets.log = '<your revset>'` or add custom aliases that invoke `jj log` with another revset

**Comment by martinvonz** [comment] 2024-09-22 20:51
Yes, you can change the set of commits you see, as @noahmayr suggested. Maybe that will help a bit. We don't have a way of specifying a particular sorting. I don't think we'll want to support some generic way of sorting commits, but we could potentially change the default way of sorting commits to be something more useful. Feel free to file a bug with a proposal. @yuja suggested on Discord to possibly prioritize `@`. I suggested to sort by generation number (distance to the root).
