### ISSUE TITLE
private-commits setting prevents pushing allowed bookmarks

### ISSUE THREAD

**Issue by istudyatuni** [martinvonz/jj#5053] opened 2024-12-08 10:06 UTC
## Description

When config contains

```toml
git.private-commits = "bookmarks(glob:'local/*')"
```
and repo has at least one matching bookmark, jj won't push any bookmarks

## Steps to Reproduce the Problem

```sh
#!/usr/bin/env sh
set -euo pipefail

jj -V

target="$(mktemp -d)"
source="$(mktemp -d)"

echo target: $target
echo source: $source

cd "$target" && git init --bare .
cd "$source" && jj git init
jj git remote add origin "$target"
jj config set --repo "git.private-commits" "bookmarks(glob:'local/*')"
jj desc -m 'a' && jj bookmark create a && jj new
jj desc -m 'a' && jj bookmark create local/a && jj new
jj desc -m 'b' && jj bookmark create b && jj new

jj log
jj git push -N
```

## Expected Behavior
Bookmarks `a` and `b` are pushed

## Actual Behavior
None bookmarks are pushed

## Specifications

- Platform: NixOS
- Version: v0.24.0

**Comment by yuja** [comment] 2024-12-08 11:53
It works as intended. `private-commits` doesn't filter bookmarks, but commits to be pushed.

You might also be interested in the following thread.
https://github.com/martinvonz/jj/pull/4871#issuecomment-2521250637

Since jj 0.24.0, new bookmarks won't be pushed by default. I think that's the behavior you wanted. This behavior might change in later release because apparently people want to do just `jj git push` to push new bookmarks to remote.

**Comment by yuja** [comment] 2024-12-13 13:43
The feature works as intended, so closing.

**Closed by yuja** 2024-12-13 13:43 UTC
