### ISSUE TITLE
FR: add additional information after conflict markers

### ISSUE THREAD

**Issue by poliorcetics** [martinvonz/jj#3416] opened 2024-04-01 15:42 UTC
**Is your feature request related to a problem? Please describe.**

Example of a conflict currently:

```rust
<<<<<<<
%%%%%%%
-        let git: Box<dyn DiffProvider> = Box::new(Git);
-        let providers = vec![git];
+        let providers = vec![Git.into()];
+++++++
        #[cfg(feature = "git")]
        let git: Box<dyn DiffProvider> = Box::new(git::Git);
        let providers = vec![
            #[cfg(feature = "git")]
            git,
        ];
>>>>>>>
```

The issue here is that I don't remember where I was coming from since it's been some time since I last touched this.

**Describe the solution you'd like**

Adding some more information allowing to know what comes from where and to look for information could be very useful.

Suggestion:

```rust
<<<<<<< base: wuurqlntozxqr (main); conflict: uvponskzxlpzot
%%%%%%% diff: wuurqlntozxqr (-) to uvponskzxlpzot (+)
-        let git: Box<dyn DiffProvider> = Box::new(Git);
-        let providers = vec![git];
+        let providers = vec![Git.into()];
+++++++ added in uvponskzxlpzot
        #[cfg(feature = "git")]
        let git: Box<dyn DiffProvider> = Box::new(git::Git);
        let providers = vec![
            #[cfg(feature = "git")]
            git,
        ];
>>>>>>>
```

In practice something of the form:

```
<<<<<<< base: CHANGE_ID_BASE (branch names, if any) ; conflict: CHANGE_ID_CONFLICT
%%%%%%% diff: CHANGE_ID_BASE (-) to CHANGE_ID_CONFLICT (+)
------- removed in CHANGE_ID_X
+++++++ added in CHANGE_ID_X
```

**Describe alternatives you've considered**

1. Do nothing: this works but information is missing that could be useful to understand conflict markers

**Additional context**

Git does something similar:

```bash
$ git init \
  && git branch -m main \
  && echo -e "Foo\nHello" > file.txt \
  && git add file.txt \
  && git commit -m "a" \
  && git branch new-branch \
  && git switch new-branch \
  && echo -e "Bar\nFarwell" > file.txt \
  && git add file.txt \
  && git commit -m "b" \
  && git switch main \
  && echo -e "Bar\nHello" > file.txt \
  && git add file.txt \
  && git commit -m "c" \
  && git merge new-branch
```

```bash
$ cat file.txt

Bar
<<<<<<< HEAD
Hello
||||||| 492f92b
Foo
Hello
=======
Farwell
>>>>>>> new-branch
```

Here this is a merge so:

- `HEAD` is the local change
- `492f92b` is the common ancestor
- `new-branch` is the remote change being merged

**Comment by ilyagr** [comment] 2024-04-01 16:41
I'm actually working on a simpler version of this, see https://github.com/martinvonz/jj/issues/1176#issuecomment-2014044247. I think this is a duplicate of that bug.

**Closed by ilyagr** 2024-04-01 16:41 UTC
Labels: enhancement, polish🪒🐃
