### ISSUE TITLE
FR: Add `jj new` flag that moves branches pointing to parent(s) to the newly created change

### ISSUE THREAD

**Issue by tp-woven** [martinvonz/jj#2534] opened 2023-11-06 03:12 UTC
Similar to Git, where committing repeatedly to a branch keeps the branch pointing to the head, it would be useful if `jj new` could move branches to the new change, so that `jj git push` on a feature with multiple chained commits continues to work.

**Comment by martinvonz** [comment] 2023-11-06 05:24
Sounds like a duplicate of #2338. Feel free to open if you think this is different.

**Closed by martinvonz** 2023-11-06 05:24 UTC
