### ISSUE TITLE
FR: Is there a way to use jj programatically?

### ISSUE THREAD

**Issue by jdmarshall** [martinvonz/jj#3615] opened 2024-05-02 23:03 UTC
**Is your feature request related to a problem? Please describe.**

Providing a GUI for JJ, but ideally also to be able to use JJ as backing store for document edits (eg, wiki edit history)

**Describe the solution you'd like**
API for performing actions with jj, instead of trying to wrap the CLI. 

**Describe alternatives you've considered**

**Additional context**

**Comment by matts1** [comment] 2024-05-03 02:28
There's a fair amount of existing discussions in this area.
#3034 and #3601 discuss how to go about it

https://github.com/gulbanana/gg is a gui for jj that uses the `jj-lib` crate under the hood. In the long term, I'd like to stop people from being able to use the `jj-lib` crate's internals directly by providing a proper, formal API that is well-documented and stable, but for now it's the only way to do so.

**Comment by ilyagr** [comment] 2024-05-03 02:31
Another option is to use the CLI and templates, like https://github.com/noahmayr/vjj

**Comment by matts1** [comment] 2024-05-14 04:02
I'll close this since it seems to be a duplicate of #3034

**Closed** 2024-05-14 04:03 UTC
