### ISSUE TITLE
FR: Update author timestamp when initally committing change

### ISSUE THREAD

**Issue by scott2000** [martinvonz/jj#3008] opened 2024-02-10 03:46 UTC
**Is your feature request related to a problem? Please describe.**
When I look at the author timestamp of a commit, I usually expect to see the timestamp when I first committed code for that change. However, the working copy commit seems to always set the author timestamp when it is first created (even if no changes have been made yet). For instance, I might do `jj new` after finishing working on a feature on Feb 9th, then not work on that project for a week, then start working on a new feature on Feb 16th, but when I commit my changes, the author timestamp will show Feb 9th.

**Describe the solution you'd like**
To me it seems like the author timestamp should not be "finalized" until a description is set on the commit. Like whenever a commit goes from having an empty description to having a non-empty description, the author timestamp should be reset. Or perhaps instead it could happen when the commit itself goes from being empty to being non-empty.

**Describe alternatives you've considered**
I could do `jj describe --reset-author --no-edit` to reset the author when I start working on a new feature on an existing working copy commit, or `jj abandon` to create a new commit entirely, but I might forget to do that. I could also just ignore the author timestamp. `jj commit` doesn't appear to support a `--reset-author` option, so I don't think I could set an alias for that.

**Comment by ilyagr** [comment] 2024-02-10 07:01
This was discussed previously (and without a conclusion) in https://github.com/martinvonz/jj/issues/2000.

Setting the date when a commit becomes non-empty OR gains a description is "option 1" in there. I'm not sure just depending *just* on the description is as good, but I'm not entirely sure. "Option 2" there is to update the author date on every edit except for rebases.

I think I'm leaning towards "option 1" at the moment, but I haven't thought about this for a while.

**Comment by ilyagr** [comment] 2024-02-10 07:01
In fact, I'll close this as a duplicate of #2000.

**Closed by ilyagr** 2024-02-10 07:01 UTC
