### ISSUE TITLE
FR: merge tool edit conflict marker as 3-way

### ISSUE THREAD

**Issue by stacyharper** [martinvonz/jj#4395] opened 2024-09-05 09:18 UTC
**Is your feature request related to a problem? Please describe.**

I'm accustomed to using a simple text editor as git resolver (kakoune). But jj output the change from base in a different way, and less readable to me.

```
A 
B 
<<<<<<< Conflict 1 of 1 
%%%%%%% Changes from base to side #1 
-c 
+C 
+++++++ Contents of side #2 
C 
D 
>>>>>>> Conflict 1 of 1 ends 
```

**Describe the solution you'd like**

Either the default change, or an additional option, allow jj to prepare the output file more this way:

```
A 
B 
<<<<<<< Contents of side #1
C
%%%%%%% Contents of base
c
+++++++ Contents of side #2 
C 
D 
>>>>>>>
```

**Comment by martinvonz** [comment] 2024-09-05 16:24
Duplicate of #823

**Closed by martinvonz** 2024-09-05 16:24 UTC
