### ISSUE TITLE
Can't clone GitHub repo with ssh on Windows

### ISSUE THREAD

**Issue by St0wy** [martinvonz/jj#4875] opened 2024-11-15 17:42 UTC
## Description

When cloning I get : 

```
jj git clone git@github.com:St0wy/Learn-Direct3D-11.git
Fetching into new repo in "\\?\C:\dev\odin\Learn-Direct3D-11"
Error: failed to authenticate SSH session: ; class=Ssh (23)
Hint: Jujutsu uses libssh2, which doesn't respect ~/.ssh/config. Does `ssh -F /dev/null` to the host work?
```

I have an RSA key setup that works with git clone.

`ssh -F /dev/null git@github.com` also seems to work.

```
ssh -F /dev/null git@github.com
PTY allocation request failed on channel 0
Hi St0wy! You've successfully authenticated, but GitHub does not provide shell access.
```

Enabling debug output seems to show that it found the key, maybe it's the username part that is wrong ?

```
2024-11-15T20:27:47.544551Z  INFO run_command:fetch{remote_name="origin" branch_names=[Substring("")] git_settings=GitSettings { auto_local_bookmark: false, abandon_unreachable_commits: true } depth=None}: jj_lib::git: trying ssh_key username="git" path="C:\\Users\\stowy\\.ssh\\id_rsa"
```

## Steps to Reproduce the Problem

1. Clone a GitHub repo on Windows via ssh

## Expected Behavior

Should clone the repo without error.

## Actual Behavior

Can't clone the repo.

## Specifications

- Platform: Windows 11
- Version: 0.23.0

**Comment by St0wy** [comment] 2024-11-15 23:06
Update, using this version fixes the issue : https://github.com/martinvonz/jj/pull/3191

Should the issue be closed ?

**Comment by martinvonz** [comment] 2024-11-16 01:02
This sounds similar enough to #3322 that I think we can at least close it as a duplicate of that.

**Closed by martinvonz** 2024-11-16 01:02 UTC
