### ISSUE TITLE
FR: Show which revisions are involved in a conflict

### ISSUE THREAD

**Issue by ChrisPenner** [martinvonz/jj#4600] opened 2024-10-07 19:12 UTC
**Is your feature request related to a problem? Please describe.**
I recently rebased a branch and included multiple parents. 
Several revisions descended from that merge commit I've got a revision with new conflicts.
When opening the file to resolve conflicts I see `Conflict #1 of 3`, then `Contents of side #1` `Changes from base to side #2`, but I don't actually know which revisions `base` `side #1` and `side #3` correspond to, and can't find anywhere where this information is surfaced.

In fact, I'm not actually sure whether it's always possible to assume these 'sides' correspond to a revision. If they do I'd love to know which revisions they are, or perhaps which revisions were involved in a given conflict.

**Describe the solution you'd like**
I'm not sure it's possible, but I'd love to see:

```
<<<<<<< Conflict 1 of 3 between abcd and my-feature-branch
+++++++ Contents of abcd
  eval env denv activeThreads ustk bstk (Push ufsz bfsz uasz basz cix comb k) r nw
%%%%%%% Changes from defgh to my-feature-branch
...
>>>>>>> Conflict 1 of 3 ends
```

**Describe alternatives you've considered**
Even if `jj st` showed which files were conflicted because of which revisions that'd help, but would be slightly less helpful.

Thanks y'all! If I'm missing a better way to get this information please let me know!

**Comment by PhilipMetzger** [comment] 2024-10-07 20:10
As @ilyagr implemented this, he can help here.

**Comment by bnjmnt4n** [comment] 2024-10-07 20:39
This is a duplicate of https://github.com/martinvonz/jj/issues/1176. The current information stored in conflicted commits don't currently allow us to accurately determine which side corresponds to which original commit, due to the variety of ways conflicted commits can be created (see https://github.com/martinvonz/jj/issues/1176#issuecomment-1425018837 for a more detailed explanation).

**Closed by bnjmnt4n** 2024-10-07 20:39 UTC
Labels: enhancement
